// Word bank — [singular (bool), text]
// singular=true  → "is/was/has/verb-s" conjugation
// singular=false → "are/were/have/verb" conjugation

const WORDS = {
    nouns: [
        // Hockey-themed
        [true,  "your slapshot"],
        [true,  "your wrist shot"],
        [true,  "your five-hole"],
        [true,  "your skating"],
        [true,  "your stick handling"],
        [true,  "your backcheck"],
        [true,  "your glove hand"],
        [true,  "your chirping"],
        [true,  "your tape job"],
        [true,  "your penalty shot"],
        [true,  "your hockey sense"],
        [true,  "your gear bag"],
        [true,  "the Zamboni"],
        [true,  "the penalty box"],
        [true,  "your mullet"],
        [true,  "your fighting stance"],
        [true,  "that penalty"],
        [true,  "your power play"],
        [false, "your teammates"],
        [true,  "your bench"],
        // Classic / variety
        [true,  "a bucket of vomit"],
        [true,  "a cheap suit"],
        [true,  "a dead parrot"],
        [true,  "a cream-faced loon"],
        [true,  "a frightened schoolboy"],
        [true,  "a grunting sow"],
        [true,  "a hamster"],
        [true,  "a lazy old codger"],
        [true,  "a muppet"],
        [true,  "a platypus"],
        [true,  "a red-arsed baboon"],
        [true,  "a strange woman lying in a pond"],
        [false, "all of those animals"],
        [true,  "an English pig dog"],
        [false, "defenseless young men"],
        [false, "elderberries"],
        [true,  "homeless man's socks"],
        [true,  "Satan"],
        [true,  "some bloody minger"],
        [true,  "some dirty rag"],
        [true,  "someone insane"],
        [true,  "Stalin's jockstrap"],
        [true,  "the afterlife"],
        [false, "the communists"],
        [true,  "the meaning of life"],
        [true,  "the Queen"],
        [true,  "this conversation"],
        [true,  "this lake"],
        [true,  "this parrot"],
        [true,  "vodka"],
        [false, "you"],
        [true,  "your beloved auntie"],
        [true,  "your country"],
        [true,  "your face"],
        [true,  "your father"],
        [true,  "your hat"],
        [true,  "your house"],
        [true,  "your liver"],
        [true,  "your mother"],
        [true,  "your pimply arse"],
        [true,  "your sense of style"],
        [true,  "your sister"],
        [true,  "your son"],
        [true,  "your wife"],
    ],
    verbs: [
        // Hockey-themed
        [true,  "skate(s) like"],
        [true,  "shoot(s) like"],
        [true,  "dive(s) like"],
        [true,  "chirp(s) worse than"],
        [true,  "fight(s) like"],
        [true,  "couldn't outskate"],
        [false, "belong(s) in the minors"],
        [false, "can't stay onside"],
        [false, "can't backcheck"],
        [false, "ha(s/ve) never scored"],
        [false, "belong(s) in the stands"],
        [false, "ha(s/ve) weak ankles"],
        [false, "[is/are] a total pylon"],
        [false, "[is/are] softer than"],
        [true,  "[was/were] benched by"],
        [true,  "got(s) undressed by"],
        // Classic / variety
        [true,  "[is/are]"],
        [false, "[is/are] an ill-nurtured whey face"],
        [false, "[is/are] dull and ugly"],
        [false, "[is/are] full of eels"],
        [false, "[is/are] getting fat"],
        [false, "[is/are] minging"],
        [false, "[is/are] no more"],
        [false, "[is/are] not interesting"],
        [false, "[is/are] old"],
        [false, "[is/are] rather plain"],
        [false, "[is/are] silly"],
        [false, "[is/are] stone dead"],
        [false, "[is/are] very naughty"],
        [false, "[is/are] vile"],
        [false, "[is/are] worthless"],
        [true,  "[was/were]"],
        [true,  "[was/were] born in"],
        [true,  "[was/were] defeated by"],
        [true,  "[was/were] owned by"],
        [true,  "[was/were] teabagged by"],
        [true,  "[has/have] a steaming romp with"],
        [false, "[has/have] bad breath"],
        [false, "[has/have] not finished puberty"],
        [true,  "[has/have] worse hair than"],
        [true,  "act(s) like"],
        [true,  "admire(s) pictures of"],
        [true,  "can't exercise because of"],
        [true,  "change(s) into"],
        [true,  "dance(s) like"],
        [true,  "died because of"],
        [true,  "do(es)n't like"],
        [true,  "donated organs for"],
        [true,  "farted on"],
        [true,  "look(s) like"],
        [true,  "made a poor deal with"],
        [true,  "pose(s) nude for"],
        [true,  "probably murdered"],
        [true,  "secretly adore(s)"],
        [true,  "sit(s) next to"],
        [true,  "smell(s) of"],
        [true,  "stalked"],
        [true,  "taste(s) like"],
        [true,  "wanted to be"],
        [true,  "worked with"],
    ],
    endings: [
        // Hockey-themed
        [false, "ya beauty!"],
        [false, "bud!"],
        [false, "ya donkey!"],
        [false, "champ!"],
        [false, "pal!"],
        [false, "get off the ice!"],
        [false, "sit down!"],
        [false, "go back to the minors!"],
        [false, "you plug!"],
        [false, "you schmuck!"],
        [false, "you pylon!"],
        [false, "you duster!"],
        [false, "and you can't skate!"],
        [false, "beauty!"],
        // Classic / variety
        [false, "mate!"],
        [false, "honey!"],
        [false, "sir!"],
        [false, "and everybody knows that!"],
        [false, "and I damn you!"],
        [false, "and I have proof!"],
        [false, "and piss off!"],
        [false, "and stop being a berk!"],
        [false, "and you can't deny it!"],
        [false, "and you know it's true!"],
        [false, "because you are a spoiled brat!"],
        [false, "cockwomble!"],
        [false, "I bet!"],
        [false, "innit?!"],
        [false, "like a minging peasant!"],
        [false, "now put a sock in it!"],
        [false, "nudge nudge!"],
        [false, "pardon my French!"],
        [false, "says the fortune cookie!"],
        [false, "so go back to your seat!"],
        [false, "yeah baby!"],
        [false, "you cheeky bastard!"],
        [false, "you inbred twit!"],
        [false, "you numpty!"],
        [false, "you pillock!"],
        [false, "you pitiful mortal!"],
        [false, "you tottering fool-born hedge-pig!"],
    ],
};
