// Insult words database - ported from Rust version
const WORDS = {
    nouns: [
        [true, "a bucket of vomit"],
        [true, "a cheap suit"],
        [true, "a cheese shop"],
        [true, "a cider-drinking chav"],
        [true, "a cold sausage without mustard"],
        [true, "a cream-faced loon"],
        [true, "a dead parrot"],
        [true, "a demon's asshole"],
        [true, "a duck hunter"],
        [true, "a frightened schoolboy"],
        [true, "a grunting sow"],
        [true, "a half-eaten crumpet"],
        [true, "a hamster"],
        [true, "a horny little bunny"],
        [true, "a lazy old codger"],
        [true, "a lumberjack"],
        [true, "a muppet"],
        [true, "a piece of battered cod"],
        [true, "a platypus"],
        [true, "a public loo"],
        [true, "a red-arsed baboon"],
        [true, "a ruttish fishmonger"],
        [true, "a strange woman lying in a pond"],
        [false, "all of those animals"],
        [true, "an alien hamburger"],
        [true, "an English pig dog"],
        [true, "angry mob"],
        [true, "an ordinary pigsty"],
        [true, "Dagon"],
        [false, "defenseless young men"],
        [false, "elderberries"],
        [true, "fish 'n' chips"],
        [true, "homeless man's socks"],
        [true, "Louisiana swamp-priests"],
        [true, "Satan"],
        [true, "some bloody minger"],
        [true, "some dirty rag"],
        [true, "some dog"],
        [true, "someone insane"],
        [true, "spam"],
        [true, "Stalin's jockstrap"],
        [true, "that Thing on your doorstep"],
        [true, "the African swallow"],
        [true, "the afterlife"],
        [false, "the communists"],
        [false, "the cozzers"],
        [false, "the Deep Ones"],
        [false, "the Hell's Grannies gang"],
        [true, "the meaning of life"],
        [false, "the Nazis"],
        [true, "the Queen"],
        [true, "the Royal Family"],
        [true, "the thing you had for lunch"],
        [true, "this bloody pet shop"],
        [true, "this conversation"],
        [true, "this lake"],
        [true, "this liver"],
        [true, "this parrot"],
        [true, "this place"],
        [true, "this poor man"],
        [true, "this train"],
        [true, "vodka"],
        [false, "you"],
        [true, "your beloved auntie"],
        [true, "your country"],
        [true, "your cousin's car"],
        [true, "your face"],
        [true, "your father"],
        [true, "your favourite Bond actor"],
        [true, "your hat"],
        [true, "your house"],
        [true, "your hovercraft"],
        [true, "your husband"],
        [true, "your kettle"],
        [true, "your liver"],
        [true, "your math teacher"],
        [true, "your mother"],
        [true, "your pimply arse"],
        [true, "your seat"],
        [true, "your sense of style"],
        [true, "your sister"],
        [false, "your sins"],
        [true, "your son"],
        [true, "your wife"]
    ],
    verbs: [
        [true, "[is/are]"],
        [false, "[is/are] afraid of my minigun"],
        [false, "[is/are] an ill-nurtured whey face"],
        [false, "[is/are] an old bugger"],
        [false, "[is/are] an organ in your abdomen"],
        [false, "[is/are] deceased"],
        [false, "[is/are] dull and ugly"],
        [false, "[is/are] full of eels"],
        [false, "[is/are] getting fat"],
        [false, "[is/are] interested in photography"],
        [false, "[is/are] minging"],
        [false, "[is/are] no more"],
        [false, "[is/are] not a part of Europe"],
        [false, "[is/are] not interesting"],
        [false, "[is/are] not migratory"],
        [false, "[is/are] not my creation"],
        [false, "[is/are] not Serious"],
        [false, "[is/are] old"],
        [false, "[is/are] racist"],
        [false, "[is/are] rather plain"],
        [false, "[is/are] rude"],
        [false, "[is/are] scratched"],
        [false, "[is/are] silly"],
        [false, "[is/are] stone dead"],
        [false, "[is/are] very naughty"],
        [false, "[is/are] vile"],
        [false, "[is/are] where you can sit"],
        [false, "[is/are] worthless"],
        [true, "[was/were]"],
        [true, "[was/were] born in"],
        [false, "[was/were] burnt like a witch"],
        [true, "[was/were] defeated by"],
        [false, "[was/were] in jail"],
        [true, "[was/were] owned by"],
        [true, "[was/were] teabagged by"],
        [true, "[has/have] a steaming romp with"],
        [false, "[has/have] an unsightly face"],
        [false, "[has/have] bad breath"],
        [false, "[has/have] bum cancer"],
        [false, "[has/have] no life experience"],
        [false, "[has/have] not finished puberty"],
        [false, "[has/have] not so much brain as ear wax"],
        [false, "[has/have] only local multiplayer"],
        [false, "[has/have] tiny feet"],
        [true, "[has/have] worse hair than"],
        [true, "act(s) like"],
        [true, "admire(s) pictures of"],
        [true, "ate Yul Brynner with"],
        [false, "belong(s) in one of those cages"],
        [false, "bother(s) me"],
        [false, "bring(s) insults to a sword fight"],
        [false, "can be found in Pokémon GO"],
        [false, "can lick my lead"],
        [false, "can't dance"],
        [true, "can't exercise because of"],
        [false, "can't hold liquor"],
        [false, "can't tie a tie"],
        [true, "change(s) into"],
        [true, "dance(s) like"],
        [true, "died because of"],
        [true, "do(es)n't like"],
        [false, "do(es)n't own a colour telly"],
        [true, "donated organs for"],
        [false, "eat(s) only non-gluten lembas"],
        [false, "enjoyed Batman v Superman"],
        [false, "fart(s) in your general direction"],
        [true, "farted on"],
        [true, "give(s) a butcher's hook at"],
        [false, "go(es) around murdering people"],
        [false, "had too much of Fungi from Yuggoth"],
        [false, "hide(s) in this shrubbery"],
        [false, "like(s) to flash in the park"],
        [true, "look(s) like"],
        [false, "look(s) like a sad lemur"],
        [true, "made a poor deal with"],
        [false, "make(s) fun of the Pope"],
        [false, "make(s) me sick"],
        [false, "move(s) like a pregnant yak"],
        [false, "must be fun at parties"],
        [false, "need(s) a liver transplant"],
        [false, "never heard the call of Cthulhu"],
        [false, "never partied in Moscow"],
        [false, "never watched Star Wars"],
        [false, "play(s) hidden object games"],
        [true, "pose(s) nude for"],
        [false, "pre-ordered No Man's Sky"],
        [true, "probably murdered"],
        [false, "put(s) on granny's clothing"],
        [true, "read(s) Necronomicon with"],
        [true, "secretly adore(s)"],
        [false, "send(s) you warmest pots and dishes"],
        [true, "sit(s) next to"],
        [true, "smell(s) of"],
        [true, "stalked"],
        [false, "still use(s) Windows Vista"],
        [false, "suck(s) at Overwatch"],
        [true, "support(s)"],
        [false, "swallowed a chewing gum"],
        [false, "talk(s) to strangers"],
        [true, "taste(s) like"],
        [false, "tell(s) dirty jokes at funerals"],
        [false, "used to steal from orphans"],
        [false, "vomit(s) after drinking vodka"],
        [false, "walk(s) silly"],
        [false, "wants some Wang"],
        [true, "wanted to be"],
        [false, "wear(s) second-hand clothes"],
        [false, "went to the Mountain of Madness"],
        [false, "will always be alone"],
        [false, "will be chopped to bits"],
        [false, "will be damned for eternity"],
        [false, "will murder for a seat reservation"],
        [false, "will reincarnate as a pigeon"],
        [false, "will soon kick the bucket"],
        [true, "worked with"]
    ],
    endings: [
        [false, "mate!"],
        [false, "honey!"],
        [false, "mister!"],
        [false, "ma'am!"],
        [false, "sir!"],
        [false, "lady!"],
        [false, "and everybody knows that!"],
        [false, "and I damn you!"],
        [false, "and I don't love you!"],
        [false, "and I have proof!"],
        [false, "and I'm Serious!"],
        [false, "and it's scientifically proven!"],
        [false, "and now let me finish the rites!"],
        [false, "and piss off!"],
        [false, "and stop being a berk!"],
        [false, "and that's a load of bollocks!"],
        [false, "and that's racist!"],
        [false, "and the Dead One still dreams in R'lyeh!"],
        [false, "and you can't deny it!"],
        [false, "and you know it's true!"],
        [false, "because I don't exist!"],
        [false, "because you are a spoiled brat!"],
        [false, "cockwomble!"],
        [false, "I bet!"],
        [false, "innit?!"],
        [false, "и я знаю, что ты шпион!"],
        [false, "like a minging peasant!"],
        [false, "now put a sock in it!"],
        [false, "nudge nudge!"],
        [false, "oh God, who writes this stuff?!"],
        [false, "or is it about the way I talk?!"],
        [false, "pardon my French!"],
        [false, "says the fortune cookie!"],
        [false, "so go back to your seat!"],
        [false, "so, you know, well, innit, eh?!"],
        [false, "товарищ!"],
        [false, "which is an ancient Chinese secret!"],
        [false, "which makes me stiff!"],
        [false, "which might cause death!"],
        [false, "which will make you die or go insane!"],
        [false, "yeah baby!"],
        [false, "you son of a washerwoman!"],
        [false, "you daughter of a washerwoman!"],
        [false, "you cheeky bastard!"],
        [false, "you cheeky bint!"],
        [false, "you commoner!"],
        [false, "you cross-eyed, inbred muckspout!"],
        [false, "you dickbag!"],
        [false, "you ginger!"],
        [false, "you inbred twit!"],
        [false, "you lying git!"],
        [false, "you numpty!"],
        [false, "you pillock!"],
        [false, "you pitiful mortal!"],
        [false, "you posh fopdoodle!"],
        [false, "you tottering fool-born hedge-pig!"],
        [false, "young man!"]
    ]
};
